package cencosud.poccencoregla;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Venta implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   
   private java.lang.Integer ventaMensual;
   
   private java.lang.Integer ventaComercial;
   
   private java.lang.Integer diferencia;
   
   private java.lang.Integer metaObjetivo;
   
   private java.lang.Integer premio;
   
   private java.lang.Integer rentaBruta;
   
   private java.lang.String cargo;
   
   private java.lang.Integer rentaTotal;
   
   private java.lang.Integer porcentajePremio;

   
   private Float porcetajePorCargo;

   
   private int antiguedadLocal;

   
   private java.lang.Integer rut;

   public Venta()
   {
   }

   public java.lang.Integer getVentaMensual()
   {
      return this.ventaMensual;
   }

   public void setVentaMensual(java.lang.Integer ventaMensual)
   {
      this.ventaMensual = ventaMensual;
   }

   public java.lang.Integer getVentaComercial()
   {
      return this.ventaComercial;
   }

   public void setVentaComercial(java.lang.Integer ventaComercial)
   {
      this.ventaComercial = ventaComercial;
   }

   public java.lang.Integer getDiferencia()
   {
      return this.diferencia;
   }

   public void setDiferencia(java.lang.Integer diferencia)
   {
      this.diferencia = diferencia;
   }

   public java.lang.Integer getMetaObjetivo()
   {
      return this.metaObjetivo;
   }

   public void setMetaObjetivo(java.lang.Integer metaObjetivo)
   {
      this.metaObjetivo = metaObjetivo;
   }

   public java.lang.Integer getPremio()
   {
      return this.premio;
   }

   public void setPremio(java.lang.Integer premio)
   {
      this.premio = premio;
   }

   public java.lang.Integer getRentaBruta()
   {
      return this.rentaBruta;
   }

   public void setRentaBruta(java.lang.Integer rentaBruta)
   {
      this.rentaBruta = rentaBruta;
   }

   public java.lang.String getCargo()
   {
      return this.cargo;
   }

   public void setCargo(java.lang.String cargo)
   {
      this.cargo = cargo;
   }

   public java.lang.Integer getRentaTotal()
   {
      return this.rentaTotal;
   }

   public void setRentaTotal(java.lang.Integer rentaTotal)
   {
      this.rentaTotal = rentaTotal;
   }

   public java.lang.Integer getPorcentajePremio()
   {
      return this.porcentajePremio;
   }

   public void setPorcentajePremio(java.lang.Integer porcentajePremio)
   {
      this.porcentajePremio = porcentajePremio;
   }

   public int getAntiguedadLocal()
   {
      return this.antiguedadLocal;
   }

   public void setAntiguedadLocal(int antiguedadLocal)
   {
      this.antiguedadLocal = antiguedadLocal;
   }

   public java.lang.Float getPorcetajePorCargo()
   {
      return this.porcetajePorCargo;
   }

   public void setPorcetajePorCargo(java.lang.Float porcetajePorCargo)
   {
      this.porcetajePorCargo = porcetajePorCargo;
   }

   public java.lang.Integer getRut()
   {
      return this.rut;
   }

   public void setRut(java.lang.Integer rut)
   {
      this.rut = rut;
   }

   public Venta(java.lang.Integer ventaMensual, java.lang.Integer ventaComercial,
         java.lang.Integer diferencia, java.lang.Integer metaObjetivo,
         java.lang.Integer premio, java.lang.Integer rentaBruta,
         java.lang.String cargo, java.lang.Integer rentaTotal,
         java.lang.Integer porcentajePremio, java.lang.Float porcetajePorCargo,
         int antiguedadLocal, java.lang.Integer rut)
   {
      this.ventaMensual = ventaMensual;
      this.ventaComercial = ventaComercial;
      this.diferencia = diferencia;
      this.metaObjetivo = metaObjetivo;
      this.premio = premio;
      this.rentaBruta = rentaBruta;
      this.cargo = cargo;
      this.rentaTotal = rentaTotal;
      this.porcentajePremio = porcentajePremio;
      this.porcetajePorCargo = porcetajePorCargo;
      this.antiguedadLocal = antiguedadLocal;
      this.rut = rut;
   }

}